#!/usr/bin/env node
// Regenerate README.md, llms.txt, and website data JSON from canonical assets.
// Idempotent: running twice produces no diff (CI cleanliness gate).
import fs from "fs";
import path from "path";
import { loadSkills, loadInstructions, targetTools } from "./lib/assets.mjs";
import { ROOT_DIR } from "./lib/constants.mjs";

const skills = loadSkills();
const instructions = loadInstructions();

const ACTIVATION_LABEL = {
  always: "Always on",
  glob: "File pattern",
  model: "Model-requested",
  manual: "Manual",
};

// ---------- README.md ----------
function skillsTable() {
  if (skills.length === 0) return "_No skills yet._\n";
  const rows = skills.map((s) => {
    const tools = targetTools(s.metadata).join(", ");
    return `| [\`${s.slug}\`](skills/${s.slug}/SKILL.md) | ${escapePipes(
      s.description
    )} | ${tools} |`;
  });
  return ["| Skill | Description | Tools |", "|---|---|---|", ...rows].join("\n") + "\n";
}

function instructionsTable() {
  if (instructions.length === 0) return "_No instructions yet._\n";
  const rows = instructions.map((i) => {
    const tools = targetTools(i.metadata).join(", ");
    const scope = i.activation === "glob" ? `\`${i.globs}\`` : ACTIVATION_LABEL[i.activation];
    return `| [\`${i.slug}\`](instructions/${i.slug}.instructions.md) | ${escapePipes(
      i.description
    )} | ${scope} | ${tools} |`;
  });
  return (
    ["| Instruction | Description | Applies | Tools |", "|---|---|---|---|", ...rows].join("\n") +
    "\n"
  );
}

function escapePipes(s) {
  return String(s).replace(/\|/g, "\\|").replace(/\n/g, " ");
}

const readme = `# DVT Awesome Skills

> Internal, tool-agnostic collection of DVT's reusable AI skills and coding instructions.
> **Author once → generate for GitHub Copilot, Cursor, Windsurf, Claude Code, and Kiro.**

<!-- This file is generated by \`npm run build\`. Edit canonical assets in \`skills/\` and \`instructions/\`, not here. -->

## Getting started

\`\`\`bash
git clone https://github.com/bassonrichard/dvt-awesome-skills.git
cd dvt-awesome-skills
npm install

npm run build        # regenerate README.md, llms.txt, and website data
npm run website:dev  # browse skills + instructions locally
\`\`\`

## Install into your project

\`\`\`bash
# Lay assets down in your tool's native format (run from this repo)
npm run install:tool -- --tool <copilot|cursor|windsurf|claude|kiro> --dir /path/to/your/repo
\`\`\`

Browse everything on the [internal website](website/) (\`npm run website:dev\`).

## 🎯 Skills (${skills.length})

Self-contained capabilities with progressive-disclosure references.

${skillsTable()}
## 📋 Instructions (${instructions.length})

Coding standards applied by activation mode (always / file pattern / model-requested / manual).

${instructionsTable()}
## Contributing

\`\`\`bash
npm run skill:create -- --name my-skill
npm run instruction:create -- --name my-standard --activation glob --globs "**/*.ts"
npm run validate    # CI gate
npm run build       # regenerate this file + llms.txt + website data
\`\`\`

See [CONTRIBUTING.md](CONTRIBUTING.md) and [AGENTS.md](AGENTS.md).
`;

fs.writeFileSync(path.join(ROOT_DIR, "README.md"), readme);

// ---------- llms.txt ----------
const llms = [
  "# DVT Awesome Skills",
  "",
  "> Tool-agnostic DVT AI skills and instructions, generated for Copilot, Cursor, Windsurf, Claude Code, and Kiro.",
  "",
  "## Skills",
  ...skills.map((s) => `- [${s.slug}](skills/${s.slug}/SKILL.md): ${s.description}`),
  "",
  "## Instructions",
  ...instructions.map(
    (i) => `- [${i.slug}](instructions/${i.slug}.instructions.md): ${i.description}`
  ),
  "",
].join("\n");
fs.writeFileSync(path.join(ROOT_DIR, "llms.txt"), llms);

console.log(
  `✅ Built README.md and llms.txt (${skills.length} skills, ${instructions.length} instructions).`
);
console.log("ℹ️  Run `npm run website:data` to refresh the website's data files.");
