#!/usr/bin/env node
// Regenerate README.md, llms.txt, and website data JSON from canonical assets.
// Idempotent: running twice produces no diff (CI cleanliness gate).
import fs from "fs";
import path from "path";
import { loadSkills, loadInstructions, targetTools } from "./lib/assets.mjs";
import {
  ROOT_DIR,
  REPO_NAME,
  REPO_IDENTIFIER,
  REPO_HTTPS_URL,
} from "./lib/constants.mjs";

const skills = loadSkills();
const instructions = loadInstructions();

const ACTIVATION_LABEL = {
  always: "Always on",
  glob: "File pattern",
  model: "Model-requested",
  manual: "Manual",
};

// ---------- README.md ----------
function skillsTable() {
  if (skills.length === 0) return "_No skills yet._\n";
  const rows = skills.map((s) => {
    const tools = targetTools(s.metadata).join(", ");
    return `| [\`${s.slug}\`](skills/${s.slug}/SKILL.md) | ${escapePipes(
      s.description
    )} | ${tools} |`;
  });
  return ["| Skill | Description | Tools |", "|---|---|---|", ...rows].join("\n") + "\n";
}

function instructionsTable() {
  if (instructions.length === 0) return "_No instructions yet._\n";
  const rows = instructions.map((i) => {
    const tools = targetTools(i.metadata).join(", ");
    const scope = i.activation === "glob" ? `\`${i.globs}\`` : ACTIVATION_LABEL[i.activation];
    return `| [\`${i.slug}\`](instructions/${i.slug}.instructions.md) | ${escapePipes(
      i.description
    )} | ${scope} | ${tools} |`;
  });
  return (
    ["| Instruction | Description | Applies | Tools |", "|---|---|---|---|", ...rows].join("\n") +
    "\n"
  );
}

function escapePipes(s) {
  return String(s).replace(/\|/g, "\\|").replace(/\n/g, " ");
}

const readme = `# DVT Awesome Skills

> Internal, tool-agnostic collection of DVT's reusable AI skills and coding instructions.
> **Author once → generate for GitHub Copilot, Cursor, Windsurf, Claude Code, and Kiro.**

<!-- This file is generated by \`npm run build\`. Edit canonical assets in \`skills/\` and \`instructions/\`, not here. -->

## Getting started

\`\`\`bash
git clone ${REPO_HTTPS_URL}
cd ${REPO_NAME}
npm install

npm run build        # regenerate README.md, llms.txt, and website data
npm run website:dev  # browse skills + instructions locally
\`\`\`

## Install into your project

**Option A — GitHub CLI** (requires GitHub CLI >= v2.90.0):

\`\`\`bash
gh skill install ${REPO_IDENTIFIER} <skill-name> --agent <github-copilot|cursor|windsurf|claude-code|kiro-cli>
\`\`\`

**Option B — git clone** (works on any git host, no extra tooling). Pre-built native
files live in \`installs/<tool>/<skill-name>/\`; run from your project root:

\`\`\`bash
git clone --no-checkout --depth 1 ${REPO_HTTPS_URL} .dvt-skill-tmp \\
  && git -C .dvt-skill-tmp sparse-checkout set --no-cone installs/<tool>/<skill-name> \\
  && git -C .dvt-skill-tmp checkout \\
  && cp -R .dvt-skill-tmp/installs/<tool>/<skill-name>/. . \\
  && rm -rf .dvt-skill-tmp
\`\`\`

\`<tool>\` is one of \`copilot\`, \`cursor\`, \`windsurf\`, \`claude\`, \`kiro\`. For a Claude Code
user-scope install, copy into \`~\` instead of \`.\`. The \`installs/\` tree is generated by
\`npm run build\` — don't edit it by hand.

Browse everything on the [internal website](website/) (\`npm run website:dev\`).

## 🎯 Skills (${skills.length})

Self-contained capabilities with progressive-disclosure references.

${skillsTable()}
## 📋 Instructions (${instructions.length})

Coding standards applied by activation mode (always / file pattern / model-requested / manual).

${instructionsTable()}
## Contributing

\`\`\`bash
npm run skill:create -- --name my-skill
npm run instruction:create -- --name my-standard --activation glob --globs "**/*.ts"
npm run validate    # CI gate
npm run build       # regenerate this file + llms.txt + website data
\`\`\`

See [CONTRIBUTING.md](CONTRIBUTING.md) and [AGENTS.md](AGENTS.md).
`;

fs.writeFileSync(path.join(ROOT_DIR, "README.md"), readme);

// ---------- llms.txt ----------
const llms = [
  "# DVT Awesome Skills",
  "",
  "> Tool-agnostic DVT AI skills and instructions, generated for Copilot, Cursor, Windsurf, Claude Code, and Kiro.",
  "",
  "## Skills",
  ...skills.map((s) => `- [${s.slug}](skills/${s.slug}/SKILL.md): ${s.description}`),
  "",
  "## Instructions",
  ...instructions.map(
    (i) => `- [${i.slug}](instructions/${i.slug}.instructions.md): ${i.description}`
  ),
  "",
].join("\n");
fs.writeFileSync(path.join(ROOT_DIR, "llms.txt"), llms);

console.log(
  `✅ Built README.md and llms.txt (${skills.length} skills, ${instructions.length} instructions).`
);
console.log("ℹ️  Run `npm run website:data` to refresh the website's data files.");
